sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - 'stable'
  - '7'
  - '6'
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated node || brew upgrade node; fi
